### ISSUE TITLE
openvas / gvm

### ISSUE THREAD

**Issue by AkatsukiSec** [DSecureMe/vmc#44]
Hello, 

im trying to get VMC working with OpenVas but can't find any info what versions of GMP are supported? I tried with version 20.08 which did not work out. Got connection refused on port 9390.

If you would be so kind and post some guide how to correctly set it, would be nice.

Thanks a lot.

**Comment by mwalkowski** [comment]
Hi,

Thanks for reporting, but the problem is not on the vmc side, but on your OpenVas configuration. By default, gvm listens on the unix socket, so in order to connect vmc with OpenVas  you have to improve your gvmd configuration.
In the file `/etc/lib/systemd/system/gvmd.service` change the line:

```
ExecStart=/usr/sbin/gvmd --osp-vt-update=/run/ospd/ospd.sock --listen-group=_gvmchange
```
to:
```
ExecStart=/usr/sbin/gvmd --osp-vt-update=/run/ospd/ospd.sock --listen-group=_gvm --listen 0.0.0.0 --port 9390
```
then reload and restart gvmd:
```
systemctl daemon-reload 
systemctl restart  gvmd.service
```

a new port should appear:
![image](https://user-images.githubusercontent.com/673031/163448870-c703fe02-bb0c-45df-8ae5-a4bbd0e8ea10.png)

VMC openvas configuration should look like this:
![image](https://user-images.githubusercontent.com/673031/163449032-b599c1c2-950c-4b98-9357-c005b10817ea.png)

Answering your second question: The gvm protocol version that we currently support is 9.0.

Please let me know if it worked, I will add such information to our documentation.

**Comment by AkatsukiSec** [comment]
Hey,

thanks for the awesome reply. My port is fine tho i can talk to api with
gvm-cli. It's probably just a version of a GMP. 9.0 is a bit old and
greenbone compatibility is not there between versions. I will try to
downgrade.

Thanks again.

BTW great project. I love it.

**Comment by mwalkowski** [comment]
Hey,

From the error description you gave: "connection refused" I understood that VMC cannot connect to GVM because the port is closed :)

I have updated the documentation for posterity.

If there are any other problems, feel free to open a new issue.

BTW: Thank you :)
